export default {
    LEAGUE_FETCH_REQUESTED: "LEAGUE_FETCH_REQUESTED",
    LEAGUE_FETCH_SUCCEEDED: "LEAGUE_FETCH_SUCCEEDED",

    TEAMS_FETCH_REQUESTED: "TEAMS_FETCH_REQUESTED",
    TEAMS_FETCH_SUCCEEDED: "TEAMS_FETCH_SUCCEEDED",

    TEAM_FETCH_REQUESTED: "TEAM_FETCH_REQUESTED",
    TEAM_FETCH_SUCCEEDED: "TEAM_FETCH_SUCCEEDED",

    PLAYERS_FETCH_REQUESTED: "PLAYERS_FETCH_REQUESTED",
    PLAYERS_FETCH_SUCCEEDED: "PLAYERS_FETCH_SUCCEEDED",

    FIXTURES_FETCH_REQUESTED: "FIXTURES_FETCH_REQUESTED",
    FIXTURES_FETCH_SUCCEEDED: "FIXTURES_FETCH_SUCCEEDED",

    LEAGUE_INDEX_UPDATE_REQUESTED: "LEAGUE_INDEX_UPDATE_REQUESTED",
    TEAM_PAGE_INDEX_UPDATE_REQUESTED: "TEAM_PAGE_INDEX_UPDATE_REQUESTED",
    PLAYERS_PAGE_INDEX_UPDATE_REQUESTED: "PLAYERS_PAGE_INDEX_UPDATE_REQUESTED",
    FIXTURE_INDEX_UPDATE_REQUESTED: "FIXTURE_INDEX_UPDATE_REQUESTED",
    FIXTURES_PAGE_INDEX_UPDATE_REQUESTED: "FIXTURES_PAGE_INDEX_UPDATE_REQUESTED",

    ADD_TEAM_TO_FAVOURITES_REQUESTED: "ADD_TEAM_TO_FAVOURITES_REQUESTED",
    REMOVE_TEAM_FROM_FAVOURITES_REQUESTED: "REMOVE_TEAM_FROM_FAVOURITES_REQUESTED",

    GET_TEAMS_FROM_FAVOURITES_REQUESTED: "GET_TEAMS_FROM_FAVOURITES_REQUESTED",
    GET_TEAMS_FROM_FAVOURITES_SUCCEEDED: "GET_TEAMS_FROM_FAVOURITES_SUCCEEDED",

    IS_TEAM_FAVOURITE_CHECK_REQUESTED: "IS_TEAM_FAVOURITE_CHECK_REQUESTED",

    FETCH_FAILED: "FETCH_FAILED",
};
