export default {
    LEAGUE_FETCH_REQUESTED: "LEAGUE_FETCH_REQUESTED",
    UPDATE_CURRENT_LEAGUE_INDEX: "UPDATE_CURRENT_LEAGUE_INDEX",
    LEAGUE_FETCH_SUCCEEDED: "LEAGUE_FETCH_SUCCEEDED",

    TEAMS_FETCH_REQUESTED: "TEAMS_FETCH_REQUESTED",
    TEAMS_FETCH_SUCCEEDED: "TEAMS_FETCH_SUCCEEDED",

    TEAM_FETCH_REQUESTED: "TEAM_FETCH_REQUESTED",
    TEAM_FETCH_SUCCEEDED: "TEAM_FETCH_SUCCEEDED",

    FETCH_FAILED: "FETCH_FAILED"
};