export default {
    ADD_TEAM_TO_FAVORITES_REQUESTED: "ADD_TEAM_TO_FAVORITES_REQUESTED",
    REMOVE_TEAM_FROM_FAVORITES_REQUESTED: "REMOVE_TEAM_FROM_FAVORITES_REQUESTED",

    GET_TEAMS_FROM_FAVORITES_REQUESTED: "GET_TEAMS_FROM_FAVORITES_REQUESTED",
    GET_TEAMS_FROM_FAVORITES_SUCCEEDED: "GET_TEAMS_FROM_FAVORITES_SUCCEEDED",
};
